# Generated by Django 3.1.4 on 2021-01-10 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210110_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 1, 10)),
        ),
    ]
