# Generated by Django 3.1.4 on 2021-01-14 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 1, 14)),
        ),
    ]
