# Generated by Django 3.1.4 on 2021-01-19 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210114_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 1, 19)),
        ),
    ]
