# Generated by Django 3.1.4 on 2021-01-01 09:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('session_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.FilePathField(blank=True, path='D:\\studia\\JS\\Lab\\Projekt\\app\\static')),
                ('in_offer', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name_plural': 'Food',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('cart_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cart')),
                ('food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.food')),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.order')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='menu.order'),
        ),
    ]
