# Generated by Django 3.1.4 on 2021-01-01 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210101_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.time(13, 31, 3, 869170)),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.FilePathField(blank=True, path='D:\\studia\\JS\\Lab\\Projekt\\menu\\static'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 1)),
        ),
    ]
