# Generated by Django 3.1.4 on 2021-01-01 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210101_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.time(13, 31, 52, 928124)),
        ),
    ]
