# Generated by Django 3.1.4 on 2021-01-01 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210101_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.time(13, 38, 32, 602736)),
        ),
    ]
