# Generated by Django 3.1.4 on 2021-01-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_food_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.FilePathField(blank=True, path='D:\\studia\\JS\\Lab\\Projekt\\menu\\static\\img'),
        ),
    ]
