# Generated by Django 3.1.4 on 2021-01-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20210114_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.FilePathField(blank=True, path='D:\\studia\\JS\\Lab\\Projekt\\menu\\static\\food'),
        ),
    ]
